#!/bin/bash
#SBATCH -N 16 -n 16 -J paratreet -p normal -t 06:00:00 -o out -e err

make clean > /dev/null
make CHARM_HOME=$HOME/charm-ofi > /dev/null
./charmrun ./paratreet -f ../inputgen/10m.tipsy -p 100 +p48 ++ppn 3 +setcpuaffinity 0
