#!/bin/bash
#SBATCH -N 16 -n 16 -J paratreet -p normal -t 06:00:00 -o out -e err


make CHARM_HOME=$HOME/charm-ofi MAKE_OPTS="-DGROUP_CACHE" proj -j4 > /dev/null
./charmrun ./paratreet -f ../inputgen/10m.tipsy -p 100 +p48 ++ppn 3 +setcpuaffinity 0 +traceoff +traceroot logs +logsize 10000000
