#!/bin/bash
#SBATCH -N 4 -n 4 -J paratreet -p normal -t 02:00:00 -o out -e err


# using charm++ v6.10.1 ofi-linux_x86_64(-smp)

# test-204-3-smp (204 = 68 * 3)
#./charmrun ./paratreet -f ../inputgen/10m.tipsy -p 100 +logsize 10000000 +p 204 ++ppn 3 +setcpuaffinity 0

# test-10-nosmp
#./charmrun ./paratreet -f ../inputgen/10m.tipsy -p 100 +logsize 100000000 +p10

# test-12-3-smp
#./charmrun ./paratreet -f ../inputgen/10m.tipsy -p 100 +logsize 100000000 +p12 ++ppn 3 +setcpuaffinity 0

# test-12-nosmp
#./charmrun ./paratreet -f ../inputgen/10m.tipsy -p 100 +logsize 100000000 +p12
